# Generated by Django 3.0.3 on 2020-03-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TwitterAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=50)),
                ("account_username", models.CharField(max_length=15)),
                ("account_url", models.URLField()),
                ("most_used_word", models.CharField(max_length=50)),
                ("most_used_word_frequency", models.IntegerField()),
                (
                    "positive_to_negative_ratio",
                    models.DecimalField(decimal_places=2, max_digits=2),
                ),
            ],
        ),
    ]
