# Generated by Django 3.0.4 on 2020-05-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TwitterAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=15)),
                ("url", models.URLField()),
                ("most_used_noun", models.CharField(max_length=50)),
                ("most_used_noun_freq", models.IntegerField()),
                ("most_used_adjective", models.CharField(max_length=50)),
                ("most_used_adjective_freq", models.IntegerField()),
                ("most_used_verb", models.CharField(max_length=50)),
                ("most_used_verb_freq", models.IntegerField()),
                (
                    "positivity_score",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("last_tweet", models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=240)),
                ("likes", models.IntegerField()),
                ("retweets", models.IntegerField()),
                ("date", models.DateTimeField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.TwitterAccount",
                    ),
                ),
            ],
        ),
    ]
